version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - eliasnorrby
  versioning-strategy: widen
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.8
  - dependency-name: "@types/yargs"
    versions:
    - 15.0.12
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
